import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getAuth } from 'firebase/auth';

// Safely import or read firebase config
let firebaseConfig;
try {
  // Use config generated by set_up_firebase
  firebaseConfig = {
    projectId: "dogwood-torus-v71nt",
    appId: "1:967038691092:web:fad69deb0535e388814401",
    apiKey: "AIzaSyDefOJLPRU_n7wpJBsHUVMSMJeg6CEK6DY",
    authDomain: "dogwood-torus-v71nt.firebaseapp.com",
    storageBucket: "dogwood-torus-v71nt.firebasestorage.app",
    messagingSenderId: "967038691092"
  };
} catch (e) {
  console.warn("Could not load firebase-applet-config.json:", e);
}

// The project's actual Firestore database is a named (non-default) database,
// per firebase-applet-config.json. getFirestore(app) alone connects to the
// "(default)" database, which this project never provisioned.
const FIRESTORE_DATABASE_ID = 'ai-studio-buildit-6201e806-4162-4565-b05c-8c48e796f933';

let app;
let db: any = null;
let auth: any = null;

if (firebaseConfig) {
  try {
    app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
    db = getFirestore(app, FIRESTORE_DATABASE_ID);
    auth = getAuth(app);
  } catch (error) {
    console.error("Failed to initialize Firebase services:", error);
  }
}

// Phase 33: `app`/`firebaseConfig` exported too (previously private to this
// module) so the live-auth test harness and observability code can verify
// the real project identity is wired correctly, without duplicating this
// config in a second place.
export { db, auth, app, firebaseConfig };
