/**
 * Screen registry — Phase 03.
 *
 * GENERATED, then hand-reviewable: produced by cross-referencing
 * docs/architecture/screen-inventory.csv (Phase 01) against the workflow
 * definitions in src/workflows/definitions/*.ts. Every one of the 189
 * screens in src/components is classified into exactly one ScreenKind.
 * Screens matching a workflow skeleton stage carry workflow/stage/
 * entryCondition/completionEvent/nextStages/exceptionStages pulled
 * directly from that workflow's transitions, so this registry and the
 * state machines can never silently drift apart for those screens.
 *
 * Screens NOT yet matched to a workflow stage (kind !== 'workflow_step')
 * are classified as supporting_tool / configuration / dashboard_control /
 * report / exception_handling / document_detail by name-based heuristic.
 * This is a first-pass, intentionally conservative classification meant
 * to be refined screen-by-screen as Phases 08-10 actually wire each
 * surface to the engine — see docs/architecture/03-workflows.md.
 *
 * Do not hand-edit generated fields without also updating the source of
 * truth (the CSV and/or the workflow definitions) — re-run the generator
 * described in that doc instead, to keep this file and the state
 * machines consistent.
 */

import type { ScreenDefinition } from './types';

export const screenRegistry: ScreenDefinition[] = [
  {
    screenId: "AdvancePaymentRetentionScreen",
    file: "src/components/AdvancePaymentRetentionScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AlertsExceptionsDashboard",
    file: "src/components/AlertsExceptionsDashboard.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "ApiIntegrationManagementScreen",
    file: "src/components/ApiIntegrationManagementScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AppVersionChangelogFeedbackScreen",
    file: "src/components/AppVersionChangelogFeedbackScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "Firestore",
  },
  {
    screenId: "ApplicantDataCollectionScreen",
    file: "src/components/ApplicantDataCollectionScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "ApplicantScreeningScreen",
    file: "src/components/ApplicantScreeningScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AuditLogAutomatedActionsScreen",
    file: "src/components/AuditLogAutomatedActionsScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AutoNegotiationBotConfig",
    file: "src/components/AutoNegotiationBotConfig.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "AutoPoTriggerRules",
    file: "src/components/AutoPoTriggerRules.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AutoReconciliationScreen",
    file: "src/components/AutoReconciliationScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "reconciled",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"reconciled\" step of the payment workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "PAYMENT_RECONCILED",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AutomatedPayoutDisbursementScreen",
    file: "src/components/AutomatedPayoutDisbursementScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "AutomatedSequenceBuilder",
    file: "src/components/AutomatedSequenceBuilder.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "localStorage",
  },
  {
    screenId: "AutomationHealthMonitor",
    file: "src/components/AutomationHealthMonitor.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "AutomationTestingSandboxScreen",
    file: "src/components/AutomationTestingSandboxScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "BackgroundVerificationScreen",
    file: "src/components/BackgroundVerificationScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "BackupDataExportScreen",
    file: "src/components/BackupDataExportScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "BadgesMilestonesScreen",
    file: "src/components/BadgesMilestonesScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "BulkLeadImportExport",
    file: "src/components/BulkLeadImportExport.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "CallLogAutoDialer",
    file: "src/components/CallLogAutoDialer.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "localStorage",
  },
  {
    screenId: "CameraCapture",
    file: "src/components/CameraCapture.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CertificationBadgeProgressScreen",
    file: "src/components/CertificationBadgeProgressScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CommAnalytics",
    file: "src/components/CommAnalytics.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CommComplianceManager",
    file: "src/components/CommComplianceManager.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "localStorage",
  },
  {
    screenId: "CommissionRulesEngineScreen",
    file: "src/components/CommissionRulesEngineScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "Common",
    file: "src/components/Common.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "customer", "surveyor", "technician", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CommunicationTemplatesLibrary",
    file: "src/components/CommunicationTemplatesLibrary.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "localStorage",
  },
  {
    screenId: "CompanyProfileBrandingSettingsScreen",
    file: "src/components/CompanyProfileBrandingSettingsScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CompetitorBattlecard",
    file: "src/components/CompetitorBattlecard.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "ComplianceCertificationScreen",
    file: "src/components/ComplianceCertificationScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "handover",
    stage: "compliance",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"compliance\" step of the handover workflow.",
    entryCondition: "qcPassed === true (hard gate)",
    primaryAction: "Advance to next stage (final_checklist)",
    completionEvent: "COMPLIANCE_CONFIRMED",
    nextStages: ["final_checklist"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "ContestConfigurationScreen",
    file: "src/components/ContestConfigurationScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "ConversationAIBotConfig",
    file: "src/components/ConversationAIBotConfig.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "ConversionRateAnalytics",
    file: "src/components/ConversionRateAnalytics.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CounterOfferApproval",
    file: "src/components/CounterOfferApproval.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "counter_approval",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"counter_approval\" step of the quote workflow.",
    primaryAction: "Advance to next stage (sent)",
    completionEvent: "COUNTER_OFFER_APPROVED",
    nextStages: ["sent"],
    exceptionStages: ["negotiation"],
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CustomReportBuilder",
    file: "src/components/CustomReportBuilder.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CustomerAmcBookingScreen",
    file: "src/components/CustomerAmcBookingScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "handover",
    stage: "warranty_amc_active",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"warranty_amc_active\" step of the handover workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "WARRANTY_STARTED",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerDocumentVaultScreen",
    file: "src/components/CustomerDocumentVaultScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerFeedbackRatingScreen",
    file: "src/components/CustomerFeedbackRatingScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerHandoverWalkthroughScreen",
    file: "src/components/CustomerHandoverWalkthroughScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "handover",
    stage: "customer_walkthrough",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"customer_walkthrough\" step of the handover workflow.",
    primaryAction: "Advance to next stage (customer_acceptance)",
    completionEvent: "CUSTOMER_WALKTHROUGH_COMPLETED",
    nextStages: ["customer_acceptance"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerHomeDashboardScreen",
    file: "src/components/CustomerHomeDashboardScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["customer", "admin", "surveyor", "technician", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerLiveSupportChatScreen",
    file: "src/components/CustomerLiveSupportChatScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerNotificationCenterScreen",
    file: "src/components/CustomerNotificationCenterScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerObjectionHandling",
    file: "src/components/CustomerObjectionHandling.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CustomerPaymentInstallmentsScreen",
    file: "src/components/CustomerPaymentInstallmentsScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "installment_due",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"installment_due\" step of the payment workflow.",
    primaryAction: "Advance to next stage (direct_payment_initiated, loan_application_in_progress)",
    completionEvent: "PAYMENT_INITIATED",
    nextStages: ["direct_payment_initiated", "loan_application_in_progress"],
    exceptionStages: ["installment_due"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerQuickSignup",
    file: "src/components/CustomerQuickSignup.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "customer_site_confirmed",
    roles: [] as ScreenDefinition['roles'],
    purpose: "Executes the \"customer_site_confirmed\" step of the sales workflow.",
    primaryAction: "Advance to next stage (quote_started)",
    completionEvent: "QUOTE_CREATED",
    nextStages: ["quote_started"],
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "CustomerReferralProgramScreen",
    file: "src/components/CustomerReferralProgramScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "CustomerReplyInbox",
    file: "src/components/CustomerReplyInbox.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "CustomerSupportTicketScreen",
    file: "src/components/CustomerSupportTicketScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DamagedMissingPartsReportScreen",
    file: "src/components/DamagedMissingPartsReportScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "incident",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"incident\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "SUPPLIER_RESOLUTION_REQUESTED",
    exceptionStages: ["supplier_selected", "receipt"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "Dashboards",
    file: "src/components/Dashboards.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "DataPrivacyConsentManagementScreen",
    file: "src/components/DataPrivacyConsentManagementScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DealClosureConfirmation",
    file: "src/components/DealClosureConfirmation.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "closure",
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Executes the \"closure\" step of the quote workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "CONTRACT_SIGNED",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "DealTermsFinalization",
    file: "src/components/DealTermsFinalization.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "customer_acceptance",
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Executes the \"customer_acceptance\" step of the quote workflow.",
    primaryAction: "Advance to next stage (contract)",
    completionEvent: "QUOTE_ACCEPTED",
    nextStages: ["contract"],
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "DealWonCelebration",
    file: "src/components/DealWonCelebration.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "closure",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"closure\" step of the quote workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "CONTRACT_SIGNED",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "DefectSnagListScreen",
    file: "src/components/DefectSnagListScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "qc",
    stage: "snag_raised",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"snag_raised\" step of the qc workflow.",
    primaryAction: "Advance to next stage (rework)",
    completionEvent: "REWORK_ASSIGNED",
    nextStages: ["rework"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DeliveryAnalyticsScreen",
    file: "src/components/DeliveryAnalyticsScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DeliveryDelayAlertEscalationScreen",
    file: "src/components/DeliveryDelayAlertEscalationScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DeliveryPartnerManagementScreen",
    file: "src/components/DeliveryPartnerManagementScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DeliverySchedulingScreen",
    file: "src/components/DeliverySchedulingScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "dispatch",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"dispatch\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (delivery)",
    completionEvent: "SHIPMENT_ARRIVED",
    nextStages: ["delivery"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DeliverySopConfigScreen",
    file: "src/components/DeliverySopConfigScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "DigitalContractGenerator",
    file: "src/components/DigitalContractGenerator.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "contract",
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Executes the \"contract\" step of the quote workflow.",
    entryCondition: "automation creates Contract (Phase 07)",
    primaryAction: "Advance to next stage (e_sign)",
    completionEvent: "CONTRACT_SENT_FOR_SIGNATURE",
    nextStages: ["e_sign"],
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "DiscountApprovalWorkflow",
    file: "src/components/DiscountApprovalWorkflow.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "ESignatureCapture",
    file: "src/components/ESignatureCapture.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "e_sign",
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Executes the \"e_sign\" step of the quote workflow.",
    primaryAction: "Advance to next stage (closure)",
    completionEvent: "CONTRACT_SIGNED",
    nextStages: ["closure"],
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "EmergencyEscalationAlert",
    file: "src/components/EmergencyEscalationAlert.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "EscalationMatrixConfigScreen",
    file: "src/components/EscalationMatrixConfigScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "FinalHandoverChecklistScreen",
    file: "src/components/FinalHandoverChecklistScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "handover",
    stage: "final_checklist",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"final_checklist\" step of the handover workflow.",
    primaryAction: "Advance to next stage (customer_walkthrough)",
    completionEvent: "FINAL_CHECKLIST_COMPLETED",
    nextStages: ["customer_walkthrough"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "FinancialCashFlowReceivables",
    file: "src/components/FinancialCashFlowReceivables.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "FollowUpStageRules",
    file: "src/components/FollowUpStageRules.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "follow_up",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"follow_up\" step of the sales workflow.",
    primaryAction: "Advance to next stage (site_survey)",
    completionEvent: "SITE_SURVEY_SCHEDULED",
    nextStages: ["site_survey"],
    exceptionStages: ["lost", "follow_up"],
    dataSource: "localStorage",
  },
  {
    screenId: "ForgotPasswordReset",
    file: "src/components/ForgotPasswordReset.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "GeminiTools",
    file: "src/components/GeminiTools.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "GeofenceTerritoryManagement",
    file: "src/components/GeofenceTerritoryManagement.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "HandoverCompletionCertificateScreen",
    file: "src/components/HandoverCompletionCertificateScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "handover",
    stage: "certificate_issued",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"certificate_issued\" step of the handover workflow.",
    entryCondition: "customer acceptance recorded (Handover.customerAcceptedAt set) before certificate issuance",
    primaryAction: "Advance to next stage (warranty_amc_active)",
    completionEvent: "WARRANTY_STARTED",
    nextStages: ["warranty_amc_active"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "HelpFaqSupportScreen",
    file: "src/components/HelpFaqSupportScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "InstallationProgressTimelineScreen",
    file: "src/components/InstallationProgressTimelineScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "installation",
    stage: "evidence_captured",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"evidence_captured\" step of the installation workflow.",
    primaryAction: "Advance to next stage (completion)",
    completionEvent: "INSTALLATION_COMPLETED",
    nextStages: ["completion"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "InstallationSopChecklistScreen",
    file: "src/components/InstallationSopChecklistScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "installation",
    stage: "sop_execution",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"sop_execution\" step of the installation workflow.",
    primaryAction: "Advance to next stage (material_usage_logged)",
    completionEvent: "MATERIAL_USAGE_LOGGED",
    nextStages: ["material_usage_logged"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "InterviewSchedulingScreen",
    file: "src/components/InterviewSchedulingScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "InvoiceGenerator",
    file: "src/components/InvoiceGenerator.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "payment_confirmed",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"payment_confirmed\" step of the payment workflow.",
    entryCondition: "idempotencyKey required (Phase 06)",
    primaryAction: "Advance to next stage (receipt_issued)",
    completionEvent: "RECEIPT_ISSUED",
    nextStages: ["receipt_issued"],
    exceptionStages: ["disputed"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "IssueBlockerReportingScreen",
    file: "src/components/IssueBlockerReportingScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "JobDetailSiteInfoScreen",
    file: "src/components/JobDetailSiteInfoScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "installation",
    stage: "job_brief",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"job_brief\" step of the installation workflow.",
    primaryAction: "Advance to next stage (site_readiness)",
    completionEvent: "SITE_READINESS_CHECK_STARTED",
    nextStages: ["site_readiness"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "LeadAssignment",
    file: "src/components/LeadAssignment.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "assignment",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"assignment\" step of the sales workflow.",
    primaryAction: "Advance to next stage (follow_up)",
    completionEvent: "FOLLOW_UP_STARTED",
    nextStages: ["follow_up"],
    exceptionStages: ["lost"],
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadDensityHeatmap",
    file: "src/components/LeadDensityHeatmap.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "LeadDetail",
    file: "src/components/LeadDetail.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadFollowUpScheduler",
    file: "src/components/LeadFollowUpScheduler.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "follow_up",
    roles: ["admin", "surveyor"] as ScreenDefinition['roles'],
    purpose: "Executes the \"follow_up\" step of the sales workflow.",
    primaryAction: "Advance to next stage (site_survey)",
    completionEvent: "SITE_SURVEY_SCHEDULED",
    nextStages: ["site_survey"],
    exceptionStages: ["lost", "follow_up"],
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadInbox",
    file: "src/components/LeadInbox.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "lead_created",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"lead_created\" step of the sales workflow.",
    primaryAction: "Advance to next stage (qualification)",
    completionEvent: "LEAD_QUALIFIED",
    nextStages: ["qualification"],
    exceptionStages: ["lost"],
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadKanban",
    file: "src/components/LeadKanban.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "qualification",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"qualification\" step of the sales workflow.",
    primaryAction: "Advance to next stage (assignment)",
    completionEvent: "LEAD_ASSIGNED",
    nextStages: ["assignment"],
    exceptionStages: ["lost"],
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadMergeResolution",
    file: "src/components/LeadMergeResolution.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadScoring",
    file: "src/components/LeadScoring.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LeadSourceAttribution",
    file: "src/components/LeadSourceAttribution.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LegalContractTemplatesRepositoryScreen",
    file: "src/components/LegalContractTemplatesRepositoryScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "LiveActivityFeed",
    file: "src/components/LiveActivityFeed.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "LiveMapDashboard",
    file: "src/components/LiveMapDashboard.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "LiveNegotiationThread",
    file: "src/components/LiveNegotiationThread.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "negotiation",
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Executes the \"negotiation\" step of the quote workflow.",
    primaryAction: "Advance to next stage (counter_approval)",
    completionEvent: "COUNTER_OFFER_SUBMITTED",
    nextStages: ["counter_approval"],
    exceptionStages: ["rejected", "negotiation"],
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "LiveShipmentTrackingScreen",
    file: "src/components/LiveShipmentTrackingScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "dispatch",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"dispatch\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (delivery)",
    completionEvent: "SHIPMENT_ARRIVED",
    nextStages: ["delivery"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "LoanEmiApplication",
    file: "src/components/LoanEmiApplication.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "loan_application_in_progress",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"loan_application_in_progress\" step of the payment workflow.",
    primaryAction: "Advance to next stage (payment_confirmed)",
    completionEvent: "PAYMENT_RECEIVED",
    nextStages: ["payment_confirmed"],
    exceptionStages: ["payment_failed"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "LoanPartnerIntegration",
    file: "src/components/LoanPartnerIntegration.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "loan_application_in_progress",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"loan_application_in_progress\" step of the payment workflow.",
    primaryAction: "Advance to next stage (payment_confirmed)",
    completionEvent: "PAYMENT_RECEIVED",
    nextStages: ["payment_confirmed"],
    exceptionStages: ["payment_failed"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "LostLeadDisqualification",
    file: "src/components/LostLeadDisqualification.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "sales",
    stage: "lost",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"lost\" step of the sales workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "LEAD_LOST",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "ManualOverrideConsoleScreen",
    file: "src/components/ManualOverrideConsoleScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "ManufacturerProductionStatus",
    file: "src/components/ManufacturerProductionStatus.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "MapFiltersLayersControlPanel",
    file: "src/components/MapFiltersLayersControlPanel.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "localStorage",
  },
  {
    screenId: "MasterAutomationRulesDashboardScreen",
    file: "src/components/MasterAutomationRulesDashboardScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "MaterialReceivedConfirmationScreen",
    file: "src/components/MaterialReceivedConfirmationScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "receipt",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"receipt\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (reconciliation_payable)",
    completionEvent: "PAYABLE_RECONCILED",
    nextStages: ["reconciliation_payable"],
    exceptionStages: ["incident"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "MaterialUsageLoggingScreen",
    file: "src/components/MaterialUsageLoggingScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "MilestonePaymentReleaseScreen",
    file: "src/components/MilestonePaymentReleaseScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "MultiOptionComparison",
    file: "src/components/MultiOptionComparison.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "NewPartnerAggregationDashboardScreen",
    file: "src/components/NewPartnerAggregationDashboardScreen.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "NewSopRolloutNotificationScreen",
    file: "src/components/NewSopRolloutNotificationScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "NotificationTemplatesChannelsScreen",
    file: "src/components/NotificationTemplatesChannelsScreen.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "OfferOnboardingAgreementScreen",
    file: "src/components/OfferOnboardingAgreementScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "OnlinePaymentCheckout",
    file: "src/components/OnlinePaymentCheckout.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "direct_payment_initiated",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"direct_payment_initiated\" step of the payment workflow.",
    primaryAction: "Advance to next stage (payment_confirmed)",
    completionEvent: "PAYMENT_RECEIVED",
    nextStages: ["payment_confirmed"],
    exceptionStages: ["payment_failed"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "OverduePaymentEscalation",
    file: "src/components/OverduePaymentEscalation.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "installment_due",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"installment_due\" step of the payment workflow.",
    primaryAction: "Advance to next stage (direct_payment_initiated, loan_application_in_progress)",
    completionEvent: "PAYMENT_INITIATED",
    nextStages: ["direct_payment_initiated", "loan_application_in_progress"],
    exceptionStages: ["installment_due"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PartnerDeactivationExitScreen",
    file: "src/components/PartnerDeactivationExitScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PartnerDirectoryScreen",
    file: "src/components/PartnerDirectoryScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PartnerTierCategoryAssignmentScreen",
    file: "src/components/PartnerTierCategoryAssignmentScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PaymentCollectionDashboard",
    file: "src/components/PaymentCollectionDashboard.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PaymentReceiptHistory",
    file: "src/components/PaymentReceiptHistory.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "receipt_issued",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"receipt_issued\" step of the payment workflow.",
    primaryAction: "Advance to next stage (ledger_posted)",
    completionEvent: "LEDGER_POSTED",
    nextStages: ["ledger_posted"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PaymentReminderConfig",
    file: "src/components/PaymentReminderConfig.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PaymentStageScheduleSetup",
    file: "src/components/PaymentStageScheduleSetup.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "payment",
    stage: "schedule_created",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"schedule_created\" step of the payment workflow.",
    primaryAction: "Advance to next stage (installment_due)",
    completionEvent: "PAYMENT_DUE",
    nextStages: ["installment_due"],
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "PayoutApprovalQueueScreen",
    file: "src/components/PayoutApprovalQueueScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PayoutDisputeQueryScreen",
    file: "src/components/PayoutDisputeQueryScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PayoutHistoryStatementsScreen",
    file: "src/components/PayoutHistoryStatementsScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PermissionsPrimer",
    file: "src/components/PermissionsPrimer.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PhotoVideoEvidenceCaptureScreen",
    file: "src/components/PhotoVideoEvidenceCaptureScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PricingRulesMarginConfig",
    file: "src/components/PricingRulesMarginConfig.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "ProjectStatusTrackerScreen",
    file: "src/components/ProjectStatusTrackerScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "PurchaseOrderGenerator",
    file: "src/components/PurchaseOrderGenerator.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "po_drafted",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"po_drafted\" step of the procurement workflow.",
    entryCondition: "idempotencyKey required (Phase 06)",
    primaryAction: "Advance to next stage (po_approval)",
    completionEvent: "PO_SUBMITTED_FOR_APPROVAL",
    nextStages: ["po_approval"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "QcInspectorAssignmentScreen",
    file: "src/components/QcInspectorAssignmentScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "qc",
    stage: "assigned",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"assigned\" step of the qc workflow.",
    primaryAction: "Advance to next stage (inspection)",
    completionEvent: "QC_INSPECTION_STARTED",
    nextStages: ["inspection"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "QualityChecklistElectricalScreen",
    file: "src/components/QualityChecklistElectricalScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "QualityChecklistMechanicalScreen",
    file: "src/components/QualityChecklistMechanicalScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "QuizCertificationTestScreen",
    file: "src/components/QuizCertificationTestScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "QuotationAnalyticsWinLoss",
    file: "src/components/QuotationAnalyticsWinLoss.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "QuotationInputSpecs",
    file: "src/components/QuotationInputSpecs.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "localStorage",
  },
  {
    screenId: "QuotationPreview",
    file: "src/components/QuotationPreview.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "customer"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "QuotationSendEDelivery",
    file: "src/components/QuotationSendEDelivery.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "sent",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"sent\" step of the quote workflow.",
    primaryAction: "Advance to next stage (negotiation, customer_acceptance)",
    completionEvent: "QUOTE_COUNTERED",
    nextStages: ["negotiation", "customer_acceptance"],
    exceptionStages: ["rejected"],
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "QuotationTemplateBranding",
    file: "src/components/QuotationTemplateBranding.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "localStorage",
  },
  {
    screenId: "QuotationVersionHistory",
    file: "src/components/QuotationVersionHistory.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "QuotePricing",
    file: "src/components/QuotePricing.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "quote",
    stage: "pricing_margin",
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Executes the \"pricing_margin\" step of the quote workflow.",
    primaryAction: "Advance to next stage (internal_approval)",
    completionEvent: "QUOTE_PRICED",
    nextStages: ["internal_approval"],
    dataSource: "localStorage",
  },
  {
    screenId: "RecruitmentLandingScreen",
    file: "src/components/RecruitmentLandingScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "RefundDisputeManagement",
    file: "src/components/RefundDisputeManagement.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "RevenueProfitAnalytics",
    file: "src/components/RevenueProfitAnalytics.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "RewardsLeaderboardScreen",
    file: "src/components/RewardsLeaderboardScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "ReworkAssignmentScreen",
    file: "src/components/ReworkAssignmentScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "qc",
    stage: "rework",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"rework\" step of the qc workflow.",
    primaryAction: "Advance to next stage (reinspection)",
    completionEvent: "REWORK_COMPLETED",
    nextStages: ["reinspection"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "RoleSelectionWizard",
    file: "src/components/RoleSelectionWizard.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "RouteOptimizationSuggestion",
    file: "src/components/RouteOptimizationSuggestion.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SMSBroadcastDeliveryReport",
    file: "src/components/SMSBroadcastDeliveryReport.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "localStorage",
  },
  {
    screenId: "SaaSOpsSubscriptionBillingScreen",
    file: "src/components/SaaSOpsSubscriptionBillingScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "SafetyComplianceChecklistScreen",
    file: "src/components/SafetyComplianceChecklistScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SalesFunnelAnalytics",
    file: "src/components/SalesFunnelAnalytics.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "SecuritySessionManagementScreen",
    file: "src/components/SecuritySessionManagementScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SinglePersonMonitorControlPanelScreen",
    file: "src/components/SinglePersonMonitorControlPanelScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SiteDeliveryChecklistScreen",
    file: "src/components/SiteDeliveryChecklistScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "delivery",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"delivery\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (receipt)",
    completionEvent: "MATERIAL_RECEIVED",
    nextStages: ["receipt"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SiteVisitVerification",
    file: "src/components/SiteVisitVerification.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SkillMatrixGapAnalysisScreen",
    file: "src/components/SkillMatrixGapAnalysisScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SlaTimerBreachAlertScreen",
    file: "src/components/SlaTimerBreachAlertScreen.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SopDocumentRepositoryScreen",
    file: "src/components/SopDocumentRepositoryScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "StageWisePayoutTrackerScreen",
    file: "src/components/StageWisePayoutTrackerScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "StockInTransitScreen",
    file: "src/components/StockInTransitScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierCatalogPricing",
    file: "src/components/SupplierCatalogPricing.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "rfq_priced",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"rfq_priced\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (po_drafted)",
    completionEvent: "PO_CREATED",
    nextStages: ["po_drafted"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierCommunicationThreads",
    file: "src/components/SupplierCommunicationThreads.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierContractSla",
    file: "src/components/SupplierContractSla.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierDirectory",
    file: "src/components/SupplierDirectory.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "supplier_selected",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"supplier_selected\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (rfq_priced)",
    completionEvent: "RFQ_PRICED",
    nextStages: ["rfq_priced"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierDisputeResolutionScreen",
    file: "src/components/SupplierDisputeResolutionScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "exception_handling" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Exception/escalation handling surface for out-of-band situations.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierInvoiceMatchingScreen",
    file: "src/components/SupplierInvoiceMatchingScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "reconciliation_payable",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"reconciliation_payable\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "PAYABLE_RECONCILED",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierOnboarding",
    file: "src/components/SupplierOnboarding.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "SupplierOrderStatusTracking",
    file: "src/components/SupplierOrderStatusTracking.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "procurement",
    stage: "production",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"production\" step of the procurement workflow.",
    primaryAction: "Advance to next stage (dispatch)",
    completionEvent: "MATERIAL_DISPATCHED",
    nextStages: ["dispatch"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierPaymentAnalyticsScreen",
    file: "src/components/SupplierPaymentAnalyticsScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierPaymentApprovalScreen",
    file: "src/components/SupplierPaymentApprovalScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierPaymentHistoryScreen",
    file: "src/components/SupplierPaymentHistoryScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierPaymentScheduleScreen",
    file: "src/components/SupplierPaymentScheduleScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierPaymentTermsConfigScreen",
    file: "src/components/SupplierPaymentTermsConfigScreen.tsx",
    surface: "FINANCE" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SupplierPerformanceScorecard",
    file: "src/components/SupplierPerformanceScorecard.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "SupplierRatingScorecard",
    file: "src/components/SupplierRatingScorecard.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SurveyorLiveTrackingDetailView",
    file: "src/components/SurveyorLiveTrackingDetailView.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "SurveyorOnboarding",
    file: "src/components/SurveyorOnboarding.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "SystemHealthBotMonitoringScreen",
    file: "src/components/SystemHealthBotMonitoringScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TaxDeductionStatementScreen",
    file: "src/components/TaxDeductionStatementScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TaxGstComplianceScreen",
    file: "src/components/TaxGstComplianceScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TechnicianCheckInCheckOutScreen",
    file: "src/components/TechnicianCheckInCheckOutScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "installation",
    stage: "checked_in",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"checked_in\" step of the installation workflow.",
    entryCondition: "siteReadinessConfirmed === true — hard gate, Phase 09",
    primaryAction: "Advance to next stage (safety_confirmed)",
    completionEvent: "SAFETY_CONFIRMED",
    nextStages: ["safety_confirmed"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TechnicianHomeMyJobsScreen",
    file: "src/components/TechnicianHomeMyJobsScreen.tsx",
    surface: "WORK" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "installation",
    stage: "assigned",
    roles: ["technician", "admin", "surveyor", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"assigned\" step of the installation workflow.",
    primaryAction: "Advance to next stage (job_brief)",
    completionEvent: "JOB_BRIEF_VIEWED",
    nextStages: ["job_brief"],
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TechnicianLiveTrackingDetailView",
    file: "src/components/TechnicianLiveTrackingDetailView.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "document_detail" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Document or record detail/history view.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TechnicianOnboarding",
    file: "src/components/TechnicianOnboarding.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: [] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)+localStorage",
  },
  {
    screenId: "TechnicianTeamCoordinationScreen",
    file: "src/components/TechnicianTeamCoordinationScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TrainingComplianceTrackerScreen",
    file: "src/components/TrainingComplianceTrackerScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "dashboard_control" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Dashboard/overview or control surface aggregating records for a role.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TrainingFeedbackScreen",
    file: "src/components/TrainingFeedbackScreen.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "TrainingModuleLibraryScreen",
    file: "src/components/TrainingModuleLibraryScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "UserRolePermissionManagementScreen",
    file: "src/components/UserRolePermissionManagementScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "VideoInteractiveLessonPlayerScreen",
    file: "src/components/VideoInteractiveLessonPlayerScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "WarrantyAmcRegistrationScreen",
    file: "src/components/WarrantyAmcRegistrationScreen.tsx",
    surface: "OPERATIONS" as ScreenDefinition['surface'],
    kind: "workflow_step" as ScreenDefinition['kind'],
    workflow: "handover",
    stage: "warranty_amc_active",
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Executes the \"warranty_amc_active\" step of the handover workflow.",
    primaryAction: "Advance to next stage (terminal)",
    completionEvent: "WARRANTY_STARTED",
    dataSource: "DbManager(fake/local)",
  },
  {
    screenId: "WhatsAppBusinessChatConsole",
    file: "src/components/WhatsAppBusinessChatConsole.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "supporting_tool" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Supporting tool used in context of one or more workflows; not itself a required workflow step.",
    dataSource: "localStorage",
  },
  {
    screenId: "WorkerPerformanceLeaderboard",
    file: "src/components/WorkerPerformanceLeaderboard.tsx",
    surface: "CUSTOMERS" as ScreenDefinition['surface'],
    kind: "report" as ScreenDefinition['kind'],
    roles: ["admin"] as ScreenDefinition['roles'],
    purpose: "Analytics/reporting view; read-only aggregation, not a mutation step.",
    dataSource: "props-only/none-detected",
  },
  {
    screenId: "WorkflowTriggerBuilderScreen",
    file: "src/components/WorkflowTriggerBuilderScreen.tsx",
    surface: "CONTROL" as ScreenDefinition['surface'],
    kind: "configuration" as ScreenDefinition['kind'],
    roles: ["admin", "surveyor", "technician", "customer", "supplier"] as ScreenDefinition['roles'],
    purpose: "Configuration/setup screen for rules, templates, or settings that other workflow steps read.",
    dataSource: "DbManager(fake/local)",
  },
];

export function getScreen(screenId: string): ScreenDefinition | undefined {
  return screenRegistry.find(s => s.screenId === screenId);
}

export function screensForWorkflow(workflow: string): ScreenDefinition[] {
  return screenRegistry.filter(s => s.workflow === workflow);
}

export function screensForSurface(surface: ScreenDefinition['surface']): ScreenDefinition[] {
  return screenRegistry.filter(s => s.surface === surface);
}
