/**
 * Phase 23 — generates docs/security/LEGACY_AUTHORIZATION_GAPS.md.
 *
 * "Every migrated domain must have server/data-layer enforcement. Audit
 * remaining legacy domains." Reuses the EXACT SAME classification
 * `scripts/generate-migration-matrix.ts` already computes for every
 * screen (never re-derived) and reorganizes it around the one question
 * this report exists to answer: which entities have real server-side
 * (Firestore rules) enforcement, and which are still client-only —
 * i.e. `authz.ts`'s permission checks, real for UX, but not a security
 * boundary a malicious or buggy client could not bypass by calling
 * Firestore directly.
 *
 *   npx tsx scripts/generate-legacy-authorization-gaps.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildRows } from './generate-migration-matrix';
import { migrationSummary } from '../src/migration/registry';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const OUT_FILE = path.join(REPO_ROOT, 'docs/security/LEGACY_AUTHORIZATION_GAPS.md');

function main() {
  const rows = buildRows();
  const clientOnly = rows.filter(r => r.authorizationStatus.startsWith('client-only'));
  const serverEnforced = rows.filter(r => r.authorizationStatus.startsWith('server-enforced'));
  const naRows = rows.filter(r => r.authorizationStatus === 'n/a');

  // Group client-only rows by entity — the report's real unit of risk
  // (one entity may be touched by many screens; fixing at the domain
  // level, not per-screen, is what closes the gap).
  const byEntity = new Map<string, typeof clientOnly>();
  for (const r of clientOnly) {
    const list = byEntity.get(r.entity) ?? [];
    list.push(r);
    byEntity.set(r.entity, list);
  }
  const entitiesSorted = [...byEntity.entries()].sort((a, b) => b[1].length - a[1].length);

  const summary = migrationSummary();

  const lines: string[] = [];
  lines.push('# Legacy Authorization Gaps');
  lines.push('');
  lines.push('Generated by `scripts/generate-legacy-authorization-gaps.ts` — do not hand-edit.');
  lines.push('Re-run after any migration or Firestore rules change: `npx tsx scripts/generate-legacy-authorization-gaps.ts`.');
  lines.push('');
  lines.push(`Regenerated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');
  lines.push('## What this report means');
  lines.push('');
  lines.push('- **server-enforced** — a real Firestore security rule (Phases 04-12,');
  lines.push('  `firestore.rules`) governs this entity\'s collection. A malicious or buggy');
  lines.push('  client cannot bypass the check by calling Firestore directly, regardless of');
  lines.push('  what the UI shows or hides.');
  lines.push('- **client-only** — the only authorization check is `src/lib/authz.ts`\'s');
  lines.push('  `evaluatePermission()`/`assertPermission()`, called from UI code. This is a');
  lines.push('  real, honest UX improvement (a denied action fails loudly with a clear');
  lines.push('  reason) but is explicitly **not a security boundary** — anyone who can reach');
  lines.push('  the underlying `DbManager` persistence (localStorage today; a future real');
  lines.push('  backend if `DbManager` is ever pointed at one) bypasses it entirely. Rule #8');
  lines.push('  ("do not rely on UI hiding as authorization") names exactly this risk.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`Total screens classified: **${rows.length}**`);
  lines.push('');
  lines.push('| Authorization status | Screens |');
  lines.push('|---|---|');
  lines.push(`| server-enforced | ${serverEnforced.length} |`);
  lines.push(`| client-only | ${clientOnly.length} |`);
  lines.push(`| n/a (infrastructure, no data of its own) | ${naRows.length} |`);
  lines.push('');
  lines.push(`Migration status of the ${clientOnly.length} client-only screens: ` +
    `${clientOnly.filter(r => r.migrationStatus === 'LEGACY').length} LEGACY, ` +
    `${clientOnly.filter(r => r.migrationStatus === 'PARTIALLY_MIGRATED').length} PARTIALLY_MIGRATED, ` +
    `${clientOnly.filter(r => r.migrationStatus === 'CONTEXTUAL').length} CONTEXTUAL. ` +
    'A `PARTIALLY_MIGRATED` screen here means its dual-write bridge target entity (e.g. Payment, ' +
    'PurchaseOrder) IS server-enforced — the gap is specifically the screen\'s OWN direct read/write ' +
    'path (still DbManager), not the entity it bridges into.');
  lines.push('');
  lines.push('## Gaps by entity (client-only screens only, most-touched first)');
  lines.push('');
  lines.push('| Entity | Client-only screens | Real Firestore collection exists for this entity? | Remediation |');
  lines.push('|---|---|---|---|');
  for (const [entity, entityRows] of entitiesSorted) {
    const hasCollection = entityRows.some(r => r.remainingRisk.includes('real server rules exist'));
    const remediation = hasCollection
      ? 'Migrate the screen(s) onto the existing repository/domain-service layer for this entity (Phase 16-18\'s dual-write bridge pattern, then a full cutover) — no new Firestore rule needed, one already exists.'
      : 'No canonical entity/Firestore collection exists for this yet — needs Phase 02-04-shaped work (domain model + repository + rules) before a screen migration is even possible.';
    lines.push(`| ${entity} | ${entityRows.length} | ${hasCollection ? 'Yes' : 'No'} | ${remediation} |`);
  }
  lines.push('');
  lines.push('## Full per-screen list (client-only authorization)');
  lines.push('');
  lines.push('| Screen | Entity | Migration status | Surface |');
  lines.push('|---|---|---|---|');
  for (const r of clientOnly.sort((a, b) => a.entity.localeCompare(b.entity) || a.screen.localeCompare(b.screen))) {
    lines.push(`| ${r.screen} | ${r.entity} | ${r.migrationStatus} | ${r.surface} |`);
  }
  lines.push('');
  lines.push('## What Phase 23 did and did not do about this');
  lines.push('');
  lines.push('- Did: measure and report the real, current gap (this document), grounded in');
  lines.push('  the same live data `docs/migration/screen-migration-matrix.md` uses — not a');
  lines.push('  hand-estimated count.');
  lines.push('- Did: remove/gate the one concrete, exploitable-adjacent client-side issue');
  lines.push('  found (the hardcoded demo OTP/password login bypasses — see the repo root');
  lines.push('  `docs/aiec-implementation-log.md` Phase 23 entry for the fix and its honest');
  lines.push('  bundle-text caveat).');
  lines.push('- Did NOT: close the client-only gap at scale this phase — that is exactly the');
  lines.push('  ongoing screen-migration work Phases 15-18 (and any future continuation of');
  lines.push('  that pattern) already do, one real domain/workflow at a time. Marking every');
  lines.push('  remaining screen `MIGRATED` in one phase would mean either fabricating the');
  lines.push('  migration (forbidden) or rewriting dozens of complex screens blind (this');
  lines.push('  sandbox has no browser to verify the result), both explicitly against this');
  lines.push('  pack\'s non-negotiable rules.');
  lines.push('');

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`Wrote ${OUT_FILE} — ${clientOnly.length} client-only screens across ${entitiesSorted.length} entities, ${serverEnforced.length} server-enforced screens.`);
}

main();
