/**
 * Phase 23 — generates docs/security/DESTRUCTIVE_ACTIONS_INVENTORY.md.
 *
 * "Inventory destructive actions. Classify: reversible, important,
 * financial/security, irreversible. Use appropriate confirmation/
 * approval/audit. Do NOT add pointless confirmation dialogs everywhere."
 *
 * Live scan (not a re-read of Phase 12's snapshot) of every
 * `src/components/*.tsx` file for a call to a delete/remove/revoke/
 * deactivate/disable-shaped method, classified by keyword into a risk
 * tier, cross-checked for a nearby `confirm(`/`window.confirm(` call in
 * the same file as a (necessarily approximate — see the doc's own
 * caveat) proxy for "does this action ask before acting."
 *
 *   npx tsx scripts/generate-destructive-actions-inventory.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const COMPONENTS_DIR = path.join(REPO_ROOT, 'src/components');
const OUT_FILE = path.join(REPO_ROOT, 'docs/security/DESTRUCTIVE_ACTIONS_INVENTORY.md');

type Tier = 'irreversible' | 'financial_security' | 'important' | 'reversible';

const TIER_KEYWORDS: Array<[RegExp, Tier]> = [
  [/delete|revoke|purge|erase/i, 'irreversible'],
  [/refund|payout|discount|credential|permission|role|password|apikey|secret/i, 'financial_security'],
  [/deactivate|disable|suspend|cancel|terminate|reject/i, 'important'],
  [/remove/i, 'reversible'], // "remove" alone (e.g. remove one line item, remove a filter) — usually reversible/re-addable, unlike "delete"
];

function classify(matchText: string): Tier {
  for (const [re, tier] of TIER_KEYWORDS) {
    if (re.test(matchText)) return tier;
  }
  return 'reversible';
}

interface Finding {
  file: string;
  matches: string[];
  tier: Tier;
  hasConfirm: boolean;
}

function main() {
  const files = fs.readdirSync(COMPONENTS_DIR).filter(f => f.endsWith('.tsx'));
  const findings: Finding[] = [];

  for (const f of files) {
    const full = path.join(COMPONENTS_DIR, f);
    const content = fs.readFileSync(full, 'utf8');
    const matches = [...content.matchAll(/\.(delete|remove|revoke|deactivate|disable)([A-Z]\w*)?\s*\(/g)].map(m => `${m[1]}${m[2] ?? ''}`);
    const handlerMatches = [...content.matchAll(/handle(Delete|Remove|Revoke|Deactivate|Disable)(\w*)/g)].map(m => `handle${m[1]}${m[2] ?? ''}`);
    const all = [...new Set([...matches, ...handlerMatches])];
    if (all.length === 0) continue;

    // Highest tier among all matches in the file — the file's overall risk.
    const tiers = all.map(classify);
    const tierRank: Record<Tier, number> = { irreversible: 0, financial_security: 1, important: 2, reversible: 3 };
    const tier = tiers.sort((a, b) => tierRank[a] - tierRank[b])[0];

    const hasConfirm = /\bconfirm\s*\(|window\.confirm\s*\(/.test(content);
    findings.push({ file: f.replace(/\.tsx$/, ''), matches: all, tier, hasConfirm });
  }

  findings.sort((a, b) => a.tier.localeCompare(b.tier) || a.file.localeCompare(b.file));

  const byTier: Record<Tier, Finding[]> = { irreversible: [], financial_security: [], important: [], reversible: [] };
  for (const f of findings) byTier[f.tier].push(f);

  const lines: string[] = [];
  lines.push('# Destructive Actions Inventory');
  lines.push('');
  lines.push('Generated by `scripts/generate-destructive-actions-inventory.ts` — do not hand-edit.');
  lines.push('Re-run after any screen change: `npx tsx scripts/generate-destructive-actions-inventory.ts`.');
  lines.push('');
  lines.push(`Regenerated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');
  lines.push('## Method');
  lines.push('');
  lines.push('Live scan of every `src/components/*.tsx` file for a call to a');
  lines.push('delete/remove/revoke/deactivate/disable-shaped method or handler function.');
  lines.push('Classified into 4 risk tiers by keyword (a file with multiple matches is');
  lines.push('filed under its single HIGHEST tier): **irreversible** (delete/revoke/purge),');
  lines.push('**financial_security** (refund/payout/discount/credential/permission/role/');
  lines.push('password), **important** (deactivate/disable/suspend/cancel/reject),');
  lines.push('**reversible** ("remove" alone — usually a re-addable line item or filter, not');
  lines.push('permanent data loss). `hasConfirm` is an approximate proxy (any `confirm(`/');
  lines.push('`window.confirm(` call anywhere in the same file) — a real per-action check');
  lines.push('would need to trace each specific handler, which this pack\'s own rule against');
  lines.push('"pointless confirmation dialogs everywhere" argues against automating blindly.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Tier | Files | Without any confirm() in the file |');
  lines.push('|---|---|---|');
  for (const tier of ['irreversible', 'financial_security', 'important', 'reversible'] as Tier[]) {
    const list = byTier[tier];
    lines.push(`| ${tier} | ${list.length} | ${list.filter(f => !f.hasConfirm).length} |`);
  }
  lines.push('');
  lines.push(`Total: **${findings.length}** components with at least one destructive-shaped action, ` +
    `**${findings.filter(f => !f.hasConfirm).length}** with no \`confirm()\` anywhere in the file.`);
  lines.push('');
  lines.push('## Recommendation, by tier');
  lines.push('');
  lines.push('- **irreversible** and **financial_security** — SHOULD confirm before acting.');
  lines.push('  These are the tiers where a mistaken tap has a real, hard-to-undo cost.');
  lines.push('- **important** — confirm when the action affects someone else\'s active work');
  lines.push('  (e.g. deactivating a user, cancelling a job already in progress); a judgment');
  lines.push('  call per screen, not a blanket rule.');
  lines.push('- **reversible** — do NOT add a confirmation dialog by default. Per this');
  lines.push('  pack\'s own explicit rule, a dialog on every reversible action trains users to');
  lines.push('  click through them without reading, which makes the dialogs on the tiers that');
  lines.push('  actually matter LESS effective, not more.');
  lines.push('');
  for (const tier of ['irreversible', 'financial_security', 'important', 'reversible'] as Tier[]) {
    lines.push(`## ${tier}`);
    lines.push('');
    lines.push('| Screen | Matched action(s) | Has confirm() in file |');
    lines.push('|---|---|---|');
    for (const f of byTier[tier]) {
      lines.push(`| ${f.file} | ${f.matches.join(', ')} | ${f.hasConfirm ? 'yes' : 'no'} |`);
    }
    lines.push('');
  }
  lines.push('## Manual review findings (why automated detection alone is not enough)');
  lines.push('');
  lines.push('Two real findings from actually reading a sample of the flagged files, kept');
  lines.push('here because they show why this report is a starting point for human judgment,');
  lines.push('not a list to mechanically "fix" top to bottom:');
  lines.push('');
  lines.push('- **`SecuritySessionManagementScreen`** (`revokeUserSession`/`handleRevokeSession`,');
  lines.push('  tier `irreversible`) is flagged as having no `confirm()` — but it already has a');
  lines.push('  real, well-built custom confirmation MODAL (`sessionToRevoke` state + a');
  lines.push('  "Revoke Device Session?" dialog with Cancel/Confirm buttons), just not a');
  lines.push('  literal `confirm(`/`window.confirm(` call. A false positive in this script\'s');
  lines.push('  keyword scan, not a real gap — left unfixed deliberately.');
  lines.push('- **`PaymentStageScheduleSetup`**\'s `handleDeleteStage` (tier `irreversible` by');
  lines.push('  keyword) only removes a stage from an in-memory DRAFT being edited (`setStages`');
  lines.push('  React state) — nothing is persisted until a separate, later "Save Draft"');
  lines.push('  action. Genuinely reversible in practice (undo by re-adding, or simply not');
  lines.push('  saving), despite the "delete" name. Left without a confirmation dialog');
  lines.push('  deliberately, per this pack\'s own rule against pointless ones.');
  lines.push('');
  lines.push('## What Phase 23 fixed vs. reported');
  lines.push('');
  lines.push('This inventory is measured and reported in full. A small, high-confidence');
  lines.push('subset of the `irreversible` tier with NO confirm() anywhere in the file was');
  lines.push('fixed directly this phase with a native `window.confirm()` — see');
  lines.push('`docs/aiec-implementation-log.md`\'s Phase 23 entry for exactly which screens');
  lines.push('and why those specific ones. Fixing the remaining count at scale, across dozens');
  lines.push('of screens this sandbox cannot visually re-verify without a browser, is real,');
  lines.push('separate follow-up work — reported honestly here rather than left unmeasured or');
  lines.push('claimed done.');
  lines.push('');

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`Wrote ${OUT_FILE} — ${findings.length} components found, ${findings.filter(f => !f.hasConfirm).length} without any confirm().`);
}

main();
