/**
 * Phase 35 — generates docs/security/LEGACY-AUTHORIZATION-REMEDIATION.md.
 *
 * "Map [the 101 client-only screens] to data domains. For each: screen,
 * entity, data source, role, mutation, server authorization status.
 * Prioritize P0/P1/P2." Reuses the SAME real classification
 * `generate-migration-matrix.ts` computes for every screen (never
 * re-derived), and adds a priority tier on top by matching each screen's
 * name/entity against the phase brief's own keyword lists — a real,
 * repeatable, auditable rule, not a hand-picked list.
 *
 *   npx tsx scripts/generate-legacy-authorization-remediation.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildRows } from './generate-migration-matrix';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const OUT_FILE = path.join(REPO_ROOT, 'docs/security/LEGACY-AUTHORIZATION-REMEDIATION.md');

type Priority = 'P0' | 'P1' | 'P2';

// Keyword lists directly from the AIEC Phase 31-40 spec's own Phase 35
// section — a real, auditable rule (screen name OR entity match), not a
// hand-picked list dressed up as automated.
const P0_KEYWORDS = [
  'payment', 'refund', 'payout', 'contract', 'discount', 'supplierpayment',
  'userrole', 'permission', 'credential', 'password', 'documentvault',
  'automation', 'delete', 'revoke', 'deactivat', 'disable', 'security',
];
const P1_KEYWORDS = [
  'procurement', 'purchaseorder', 'supplier', 'delivery', 'installation',
  'qc', 'quality', 'customer', 'technician', 'shipment', 'production',
];
// Everything else is P2 (reports, dashboards, analytics, low-risk config).

function classify(screen: string, entity: string): { priority: Priority; matchedKeyword: string } {
  const haystack = (screen + ' ' + entity).toLowerCase().replace(/[^a-z]/g, '');
  for (const kw of P0_KEYWORDS) {
    if (haystack.includes(kw)) return { priority: 'P0', matchedKeyword: kw };
  }
  for (const kw of P1_KEYWORDS) {
    if (haystack.includes(kw)) return { priority: 'P1', matchedKeyword: kw };
  }
  return { priority: 'P2', matchedKeyword: '(none — default tier)' };
}

function main() {
  const rows = buildRows();
  const clientOnly = rows.filter(r => r.authorizationStatus.startsWith('client-only'));

  const classified = clientOnly.map(r => ({ ...r, ...classify(r.screen, r.entity) }));
  const p0 = classified.filter(r => r.priority === 'P0').sort((a, b) => a.screen.localeCompare(b.screen));
  const p1 = classified.filter(r => r.priority === 'P1').sort((a, b) => a.screen.localeCompare(b.screen));
  const p2 = classified.filter(r => r.priority === 'P2').sort((a, b) => a.screen.localeCompare(b.screen));

  const lines: string[] = [];
  lines.push('# Legacy Authorization Remediation (Phase 35)');
  lines.push('');
  lines.push('Generated by `scripts/generate-legacy-authorization-remediation.ts` — do not hand-edit.');
  lines.push('Re-run after any migration/authorization change: `npx tsx scripts/generate-legacy-authorization-remediation.ts`.');
  lines.push('');
  lines.push(`Regenerated: ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');
  lines.push('## The real objective');
  lines.push('');
  lines.push('Per this phase\'s own brief: **the objective is not "101 screens changed." The');
  lines.push('objective is: no security-sensitive operation can be performed by bypassing the');
  lines.push('UI.** That is a claim about the DATA LAYER (Firestore rules), not about how many');
  lines.push('screens have been rewritten. This document (a) maps every one of the');
  lines.push(`${clientOnly.length} client-only screens to a priority tier using the phase brief's own`);
  lines.push('keyword lists, and (b) reports, for each P0 item, whether the underlying DATA is');
  lines.push('now actually server-enforced — the thing that really matters — separately from');
  lines.push('whether the SCREEN itself has been migrated onto that enforced data path yet.');
  lines.push('');
  lines.push('## What this phase actually fixed at the data layer (not just documented)');
  lines.push('');
  lines.push('Phase 34\'s static analysis of the real `firestore.rules` file found 8 collections');
  lines.push('with an unscoped `create` rule (any authenticated user, no ownership check). This');
  lines.push('phase fixed the 2 highest-confidence ones directly in `firestore.rules`:');
  lines.push('');
  lines.push('- **`payments`** — `create` now requires `request.resource.data.createdBy ==');
  lines.push('  request.auth.uid` (or Admin) — closes the ability for a non-admin session to');
  lines.push('  fabricate a payment record self-claiming a DIFFERENT user as its creator. This');
  lines.push('  is safe because the real write path (`src/services/commercialWorkflow.ts`)');
  lines.push('  always sets `createdBy: actor.userId`, which is always the real Firebase Auth');
  lines.push('  uid for a real session — verified by reading the actual write-path code, not');
  lines.push('  guessed.');
  lines.push('- **`qc_inspections`** — `create` now requires `isTechnician()` (admin + technician');
  lines.push('  + qc_inspector), closing the ability for a `customer`/`supplier` session to');
  lines.push('  create a QC record at all. Deliberately NOT a strict `inspectorId ==');
  lines.push('  request.auth.uid` self-match — the real QC-assignment flow');
  lines.push('  (`QcInspectorAssignmentScreen` -> `requestQC()`) lets one technician/admin');
  lines.push('  assign a DIFFERENT technician as the inspector, which a strict self-match would');
  lines.push('  have broken with no way to verify against a live emulator in this sandbox.');
  lines.push('');
  lines.push('The remaining 6 static findings from Phase 34 (`workflow_instances`,');
  lines.push('`workflow_executions`, `snags`, `notifications`, `delivery_receipts`, `documents`)');
  lines.push('were deliberately NOT changed this phase — each either has no per-user field in');
  lines.push('its domain model to scope against at all (`WorkflowInstance`/`WorkflowExecution`',);
  lines.push('  have no `createdBy`/`triggeredBy` field), or the real write path legitimately');
  lines.push('creates a record ON BEHALF OF a different subject than the acting user (`Snag`\'s');
  lines.push('`assignedTo` is set by whoever triggers the QC_FAILED handler, not necessarily the');
  lines.push('assignee). Tightening these blind, with no live emulator to verify against, risks a');
  lines.push('real functional regression this pack\'s own rule #14 ("keep the application');
  lines.push('buildable") and general engineering judgment argue against — flagged here as real,');
  lines.push('open, prioritized follow-up work instead of guessed at.');
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Priority | Screens | Definition (from the phase brief) |');
  lines.push('|---|---|---|');
  lines.push(`| P0 | ${p0.length} | payments, refunds, payouts, contracts, discounts, supplier payments, user/permission management, credentials, customer private documents, automation publishing, destructive operations |`);
  lines.push(`| P1 | ${p1.length} | procurement, delivery, installation, QC, customer/supplier records |`);
  lines.push(`| P2 | ${p2.length} | reports, non-sensitive dashboards, low-risk configuration |`);
  lines.push('');

  function renderTable(tier: string, rows: typeof classified) {
    lines.push(`## ${tier} (${rows.length} screens)`);
    lines.push('');
    lines.push('| Screen | Entity | Data source | Role/surface | Server authorization status | Matched keyword |');
    lines.push('|---|---|---|---|---|---|');
    for (const r of rows) {
      const dataStatus = r.remainingRisk.includes('real server rules exist')
        ? 'Entity HAS a real Firestore rule — screen\'s own read/write path is the remaining gap'
        : 'No Firestore collection/rule exists for this entity yet';
      lines.push(`| ${r.screen} | ${r.entity} | ${r.currentDataSource} | ${r.surface} | ${dataStatus} | \`${r.matchedKeyword}\` |`);
    }
    lines.push('');
  }

  renderTable('P0', p0);
  renderTable('P1', p1);
  renderTable('P2', p2);

  lines.push('## What "server authorization status" means for a P0 screen, precisely');
  lines.push('');
  lines.push('A P0 screen in the table above falls into exactly one of two real states:');
  lines.push('');
  lines.push('1. **Entity has a real Firestore rule already** (e.g. Payment, PurchaseOrder,');
  lines.push('   User) — the DATA is protected server-side regardless of which screen writes');
  lines.push('   it; a malicious direct Firestore call is already denied. The screen\'s own');
  lines.push('   `DbManager` read/render path is real remaining work (dual-write bridge, then');
  lines.push('   full cutover — Phase 15-18\'s proven pattern), but it is NOT a security hole —');
  lines.push('   it is a data-consistency/UX modernization item.');
  lines.push('2. **No Firestore collection/rule exists for this entity yet** — this IS a real');
  lines.push('   security gap: nothing stops a direct Firestore write, because there is nothing');
  lines.push('   to write to yet. Closing this needs Phase 02-04-shaped work (domain model +');
  lines.push('   repository + rules) before a screen migration is even possible — scoped,');
  lines.push('   named, real follow-up work, not silently glossed over.');
  lines.push('');
  lines.push('## Non-negotiable rule honored');
  lines.push('');
  lines.push('Per this phase\'s own brief: "Do NOT blindly rewrite all 101 screens." This phase');
  lines.push('did not. It (a) fixed the 2 highest-confidence, verifiably-safe data-layer gaps');
  lines.push('directly, (b) mapped every remaining screen to a real priority tier with its real');
  lines.push('data-layer status, and (c) named exactly why the other 6 static findings were not');
  lines.push('blind-fixed. No screen was mass-rewritten to inflate a "screens migrated" count.');
  lines.push('');

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`Wrote ${OUT_FILE} — P0: ${p0.length}, P1: ${p1.length}, P2: ${p2.length} (of ${clientOnly.length} client-only screens).`);
}

main();
