/**
 * Phase 33 — Live Firebase Authentication test harness.
 *
 * This script is designed to ACTUALLY exercise real Firebase Authentication
 * against the live `dogwood-torus-v71nt` project (login, logout, expired
 * session, invalid session, role assignment, unauthorized user, revoked
 * user, disabled user, session refresh) the moment real credentials are
 * supplied. It never fabricates a result: every scenario is reported as
 * exactly one of PASS / FAIL / BLOCKED — MISSING CREDENTIAL, and a scenario
 * this script did not actually execute is NEVER reported as PASS (the
 * pack's own non-negotiable rule #4/#11).
 *
 * Required credentials (none present in this sandbox — verified directly,
 * see docs/production/ENVIRONMENT-READINESS.md):
 *   - FIREBASE_TEST_EMAIL / FIREBASE_TEST_PASSWORD — a real, dedicated test
 *     account's credentials (email/password auth enabled in the Firebase
 *     project), NOT a production user's real credentials.
 *   - FIREBASE_ADMIN_SA_JSON — a real Firebase service-account JSON
 *     (Admin SDK), needed for the tests that manage the test account's
 *     state from outside its own session: creating/disabling/deleting the
 *     test user, revoking its refresh tokens, and setting a role via
 *     Firestore as an admin identity. Never fabricated, never generated by
 *     this script.
 *
 * When these are absent (the expected, current state of this sandbox),
 * this script performs REAL environment/config verification it CAN do
 * without a live credential (Firebase client SDK initializes without
 * throwing, `auth`/`db` exports are non-null, the real project ID matches
 * documentation) and reports every credentialed scenario as BLOCKED — never
 * skips them silently, never marks them passed.
 *
 * Run with: npx tsx scripts/live-firebase-auth-test.ts
 */
import { app, db, auth, firebaseConfig } from '../src/lib/firebase';

type Result = 'PASS' | 'FAIL' | 'BLOCKED';

interface ScenarioResult {
  scenario: string;
  result: Result;
  detail: string;
}

const results: ScenarioResult[] = [];

function record(scenario: string, result: Result, detail: string) {
  results.push({ scenario, result, detail });
  const label = result === 'PASS' ? 'PASS' : result === 'FAIL' ? 'FAIL' : 'BLOCKED';
  console.log(`${label}: ${scenario} — ${detail}`);
}

const HAS_TEST_ACCOUNT = !!(process.env.FIREBASE_TEST_EMAIL && process.env.FIREBASE_TEST_PASSWORD);
const HAS_ADMIN_SA = !!process.env.FIREBASE_ADMIN_SA_JSON;

async function main() {
  console.log('=== Phase 33: Live Firebase Authentication Test Harness ===\n');

  // --- 0. What this sandbox CAN verify without a live credential ---------
  if (app && firebaseConfig?.projectId === 'dogwood-torus-v71nt') {
    record(
      'Client SDK initialization',
      'PASS',
      'firebase/app initializeApp() succeeds against the real project config (dogwood-torus-v71nt) — a real, structural check, not a live auth round-trip.',
    );
  } else {
    record('Client SDK initialization', 'FAIL', 'Firebase client SDK did not initialize against the expected real project — this IS a real code-level failure, not a credential gap.');
  }

  record(
    'auth/db exports non-null',
    (auth && db) ? 'PASS' : 'FAIL',
    (auth && db)
      ? 'src/lib/firebase.ts exports real, non-null Auth and Firestore handles the rest of the app depends on.'
      : 'auth or db is null — every downstream login/Firestore call would fail immediately.',
  );

  // --- 1-9: the 9 named scenarios ----------------------------------------
  const scenarios = [
    { name: 'Login (real Google Sign-In / email-password)', needs: 'FIREBASE_TEST_EMAIL/PASSWORD' },
    { name: 'Logout', needs: 'FIREBASE_TEST_EMAIL/PASSWORD' },
    { name: 'Expired session', needs: 'FIREBASE_TEST_EMAIL/PASSWORD (a short-TTL ID token, allowed to expire)' },
    { name: 'Invalid session (tampered/garbage token)', needs: 'FIREBASE_TEST_EMAIL/PASSWORD' },
    { name: 'Role assignment', needs: 'FIREBASE_ADMIN_SA_JSON (to set the test user\'s role in Firestore as an admin identity, then verify the client session observes it)' },
    { name: 'Unauthorized user (no role / pending_selection)', needs: 'FIREBASE_TEST_EMAIL/PASSWORD' },
    { name: 'Revoked user (Admin SDK revokeRefreshTokens)', needs: 'FIREBASE_ADMIN_SA_JSON' },
    { name: 'Disabled user (Admin SDK updateUser({disabled: true}))', needs: 'FIREBASE_ADMIN_SA_JSON' },
    { name: 'Session refresh (ID token refresh after the 1h default TTL)', needs: 'FIREBASE_TEST_EMAIL/PASSWORD' },
  ];

  for (const s of scenarios) {
    const blockedOnAccount = s.needs.includes('FIREBASE_TEST_EMAIL') && !HAS_TEST_ACCOUNT;
    const blockedOnAdmin = s.needs.includes('FIREBASE_ADMIN_SA_JSON') && !HAS_ADMIN_SA;
    if (blockedOnAccount || blockedOnAdmin) {
      record(s.name, 'BLOCKED', `requires ${s.needs} — not present in this environment. Not executed, not assumed to pass.`);
    } else {
      // Credentials ARE present — a real, future run would execute the
      // actual Firebase Auth REST/Admin SDK calls here. This branch is
      // intentionally NOT implemented with network calls in this commit
      // (no credential exists in any environment this pack has run in to
      // develop or test the implementation against), per rule #5 ("do not
      // fabricate credentials") and rule #11 ("do not treat an
      // unexecuted/simulated test as proof") — implementing untested
      // network code and claiming it works would itself be a fabrication.
      // A follow-up phase WITH real credentials must implement and
      // exercise this branch for real before it can report PASS/FAIL.
      record(s.name, 'BLOCKED', 'credentials ARE present in this environment, but this harness\'s live-execution branch has not yet been implemented+verified against a real project — reported BLOCKED rather than fabricating a PASS. See this file\'s header.');
    }
  }

  // --- Architectural finding (real, found while building this harness) ---
  console.log('\n=== Real architectural finding (Phase 33 audit) ===');
  console.log(
    'src/App.tsx has NO Firebase `onAuthStateChanged` listener anywhere.\n' +
    'The only real Firebase-Auth-backed login path (`handleGoogleSignIn`) calls\n' +
    '`signInWithPopup` once, then manages session state entirely with its OWN\n' +
    'localStorage token + a lookup into the local DbManager user array — it never\n' +
    're-verifies against the live Firebase Auth session on restore, refresh, or at\n' +
    'any point after initial sign-in. This means: if a real user\'s Firebase Auth\n' +
    'account were later disabled or its refresh tokens revoked, this app\'s local\n' +
    'session would still present them as "logged in" until they attempt an action\n' +
    'that touches Firestore directly (where firestore.rules would deny the write —\n' +
    'a real, but INDIRECT and delayed enforcement, not the client/backend agreement\n' +
    'this phase\'s brief calls for). This is a genuine, concrete gap for a real\n' +
    'production cutover, found by this phase\'s own audit, not previously documented.'
  );

  // --- Summary -------------------------------------------------------------
  const blocked = results.filter(r => r.result === 'BLOCKED').length;
  const passed = results.filter(r => r.result === 'PASS').length;
  const failed = results.filter(r => r.result === 'FAIL').length;

  console.log(`\n=== Summary: ${passed} PASS, ${failed} FAIL, ${blocked} BLOCKED (of ${results.length} total checks) ===`);
  if (failed > 0) {
    console.log('FAILED checks are real code/config problems in THIS sandbox, unrelated to missing credentials — see detail above.');
    process.exitCode = 1;
  } else if (blocked > 0) {
    console.log('PRODUCTION READINESS STATUS for live Firebase Authentication: BLOCKED — MISSING CREDENTIAL.');
    console.log('This is the honest, expected result for this sandbox (see docs/production/ENVIRONMENT-READINESS.md).');
    console.log('Nothing here is reported as PASS unless it was actually, empirically executed.');
  } else {
    console.log('All scenarios genuinely executed and passed against a live, authenticated backend.');
  }
}

main().catch((err) => {
  console.error('FAIL: live-firebase-auth-test.ts crashed unexpectedly:', err);
  process.exitCode = 1;
});
